### ISSUE TITLE
Improve default configuration

### ISSUE THREAD

**Issue by zenangst** [zenangst/KeyboardCowboy#243]
If the user selects to use the recommend default setup.
They should receive some example workflows, to get a flying start.

**Comment by Din0Git** [comment]
Is there a way to start over aka import the recommend default setup after i deleted it?
Did try uninstalling and deleting left overs but i cant get the startscreen back.

**Comment by zenangst** [comment]
@Din0Git if you delete your .keyboard-cowboy.json file that is located in your Home folder. Then you should get the option to use the started shortcuts.
