### ISSUE TITLE
Installing the App

### ISSUE THREAD

**Issue by pzeepzee** [zenangst/KeyboardCowboy#273]
Hi, saw a recommendation for this app on twitter through the creator of PastePal, just wondering if you will consider allowing an easy installation via the default method on Mac or is it going to remain an Homebrew installation only? Thanks

**Comment by zenangst** [comment]
Hey @pzeepzee, I'm not sure I understand what you mean here?
Each release has a `.dmg` attached to them.

The latest release can be found here: https://github.com/zenangst/KeyboardCowboy/releases/download/3.3.1/Keyboard.Cowboy.3.3.1.dmg

The homebrew related instructions in the README is about development of the application, not installation 😎
