### ISSUE TITLE
Monterey compatible?

### ISSUE THREAD

**Issue by onderk-motion** [zenangst/KeyboardCowboy#274]
Hello, thank you for the release. 

I want to try, but I'm on macOS Monterey, and Keyboard Cowboy is not working with it.

If technically possible, can you make it compatible with Monterey?

Thank you

**Comment by onderk-motion** [comment]
Thank you for getting back to me. I'll wait :)

**Comment by zenangst** [comment]
Seems like Monterey is a no-go (at first glance).

The usage of `openWindow` is kind of core for the apps UI I'm afraid.
```
'openWindow' is only available in macOS 13.0 or newer
```

**Comment by onderk-motion** [comment]
I understand. Thank you for your efforts :)
