### ISSUE TITLE
Add support for holding a key as a shortcut

### ISSUE THREAD

**Issue by rakalex** [zenangst/KeyboardCowboy#332]
Is it possible to add a hold (like 1-2 seconds) as a shortcut to run the app?

**Comment by rakalex** [comment]
Yes, you understood it correctly, got it, thank you.

**Comment by zenangst** [comment]
@rakalex I'm also guessing that it's modifier keys (like control, option, command) that you want to hold down, not regular keys?

**Comment by rakalex** [comment]
no, so basically the idea was - I have a MacBook m1, which has F5(has mic icon on it), so when I hold it, it runs the Siri. I also have a magic keyboard with a numeric keypad (the old one, without a fingerprint) and it doesn't support that key. So I want to replicate it, but couldn't/

**Comment by zenangst** [comment]
I might know how to support this. I'll put it on my list to investigate. Working on speeding up type command at the moment 😎

https://github.com/zenangst/KeyboardCowboy/issues/334

**Comment by zenangst** [comment]
@rakalex small update here.

I've made the model and view layer for setting a delayed invocation when setting up a keyboard trigger. It looks like this right now.

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/45c50212-d2c4-4b70-9f3b-c610df5b2930)

This would mean that when holding F5, it will wait 1 seconds until the commands actually run. So if you were to let go before, it would simply cancel the execution. Still ironing out the kinks with the actual logic implementation.

Gonna make some dinner now but I will continue after that, I'll keep you posted 😎

**Comment by rakalex** [comment]
Nice progress, I like it 👍

**Comment by zenangst** [comment]
@rakalex More progress.


https://github.com/zenangst/KeyboardCowboy/assets/57446/a86210be-8476-417f-b0dc-8bf047caa822

So here I'm holding down F5 for 2 seconds.
This is what you were after right?

**Comment by rakalex** [comment]
yes, exactly! Nice job 👍

**Comment by zenangst** [comment]
@rakalex good news, `3.10.0` is out.

https://github.com/zenangst/KeyboardCowboy/releases/tag/3.10.0
