### ISSUE TITLE
Add KeyboardCowboy to the Homebrew repository

### ISSUE THREAD

**Issue by Fischmuetze** [zenangst/KeyboardCowboy#333]
Would be fabulous to have KeyboardCowboy in the Homebrew repository for an easier install/update

**Comment by zenangst** [comment]
That would indeed be very nice :)
I'm unsure if I'm eligible to add a my own application as a formula or if someone else needs to do it.

**Comment by zenangst** [comment]
@Fischmuetze also, Keyboard Cowboy uses Sparkle, so you should be notified about updates.
But homebrew would also be neat.

**Comment by Fischmuetze** [comment]
Sparkle, yes I know, but Homebrew is the easiest way to install and above all: update all the apps on your Mac with one command and to a time point that fits for you ...

**Comment by Fischmuetze** [comment]
https://github.com/Homebrew/homebrew-cask/pull/153844

**Comment by jonathanlaniado** [comment]
Any update on this? Would love to install via Homebrew.

**Comment by zenangst** [comment]
Not yet, focusing on marketing material and documentation right now. That and more contextual triggers for workflows.

But I haven’t forgotten about this one 😎

**Comment by Fischmuetze** [comment]
very sad that there is no update here :(

**Comment by zenangst** [comment]
Sorry, I know that this is important for people. I simply haven't had time to focus on this when there are multiple other things that I'd really like to get done to take the app to the next level. And there is also... life.

I know excuses, smexcues... but that is where we stand right now.
If anyone else wants to add it to Homebrew, then feel free to include it there ❤️

**Comment by zenangst** [comment]
Seems like some kind soul added Keyboard Cowboy to Homebrew, closing this issue now :)
