### ISSUE TITLE
Add fast insert text (eg via clipboard functionality)

### ISSUE THREAD

**Issue by Fischmuetze** [zenangst/KeyboardCowboy#334]
I'm using the app like the default mail example for inserting text / signatures. Insert text via the "Type" functionality is very, very slow. Would be great have the possibility to insert text directly (eg by using the clipboard)

**Comment by zenangst** [comment]
@Fischmuetze mind sharing a small screen capture so that we have the same definition of slow? I haven't used that functionality that much myself and there is most likely a lot of optimization that can be done here 😎

**Comment by zenangst** [comment]
@Fischmuetze thanks for supplying the video ❤️ I've removed it so that your info is not public anymore. Extra kudos for supplying what you would expect.

I'm gonna take a stab at improving this (when life allows). Don't know when I'll sit down and do some programming. Hopefully a time slot will reveal itself this week.

**Comment by zenangst** [comment]
@Fischmuetze good news, did some initial testing of another approach.
Check this out:

https://github.com/zenangst/KeyboardCowboy/assets/57446/53da5e78-60a8-4cb2-b890-f7672871c170

**Comment by zenangst** [comment]
I'm thinking about adding a new configuration for type command where you can select if it should be typed out or just inserted instantly. Instant is probably the saner default.

**Comment by Fischmuetze** [comment]
Looks great!

**Comment by Fischmuetze** [comment]
yes, instant as default make more sense (imho).
Serial typing could bring in special cases advantages

**Comment by zenangst** [comment]
@Fischmuetze yeah I agree, that's what I meant with it being the saner default :)
I'm gonna have to build some UI components and perform a bit of a migration of the models for this to be finalized. Might pick up where I left off tomorrow evening.

Cheers!

**Comment by zenangst** [comment]
@Fischmuetze good news, I've created a PR to add the feature here - https://github.com/zenangst/KeyboardCowboy/pull/335

Will do some more testing this evening and if all goes well, I'll push out a new version. Stay tuned 😎

**Comment by zenangst** [comment]
@Fischmuetze good news, `3.10.0` is out.

https://github.com/zenangst/KeyboardCowboy/releases/tag/3.10.0
