### ISSUE TITLE
Fullscreen leaving a bit of space on top when dock is not auto hiding

### ISSUE THREAD

**Issue by trymmern** [zenangst/KeyboardCowboy#342]
When the hide dock feature is turned off, the window gets fullscreened but moved a bit down. Expected behaviour is for it to stop "on top of" the dock but it gets moved halfway down behind the dock it seems.

Here is a screenshot showing the window after fullscreen shortcut is pressed.
<img width="1728" alt="Screenshot 2023-08-25 at 13 45 01" src="https://github.com/zenangst/KeyboardCowboy/assets/834821/040f7942-ed8f-492c-8014-3e6116211c5c">

With dock on hide-mode it works perfectly though!

**Comment by zenangst** [comment]
@trymmern Thanks for reporting this. The great thing about new features is that they are a breath of fresh air, however... they do have the tendency to introduce some quirks and bugs along the way 🤡 

Will take a look, I tend to have my Dock hidden so this seems to have slipped passed my own testing.

Going to a wedding today, might have time to look into it tomorrow .

Cheers!
