### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by Fischmuetze** [zenangst/KeyboardCowboy#376]
Ver 3.13.0 (228)

An error occurred by using "check updates"

"Update Error!
An error occurred while parsing the update feed."

<img width="249" alt="Bildschirmfoto 2023-09-17 um 11 26 53" src="https://github.com/zenangst/KeyboardCowboy/assets/19834496/0eaf5eb6-f8d8-4cd4-afa1-262882d82e86">
<img width="260" alt="Bildschirmfoto 2023-09-17 um 11 27 22" src="https://github.com/zenangst/KeyboardCowboy/assets/19834496/6381c834-2b89-4b75-98ca-81b4abab8bbf">

**Comment by zenangst** [comment]
Oh snap, I’ll look into this

**Comment by zenangst** [comment]
I've pushed an update of the `appcast.xml`, but it seems like Sparkle has a bit of caching in place, so it might not start working straight away.

**Comment by Fischmuetze** [comment]
works here now

**Comment by zenangst** [comment]
Scratch that, I just successfully updated from `3.12.0` to `3.13.0`.
Thanks for bringing this to my attention @Fischmuetze ❤️
