### ISSUE TITLE
Application selection that are not in de application folder

### ISSUE THREAD

**Issue by Din0Git** [zenangst/KeyboardCowboy#378]
Hi there, 

Found KeyboardCowboy. Love the UI and the way to make automations. 
One question/feature. Is it possible to use application that are not in the apps folder. For an example i want to make a hotkey that only works for a windows application that is running in Parallels desktop. So i need the front most application to be Parallels desktop --> Microsoft Excel (windows version) for example. 

Is there a way to make that possible?

Greetz Dino

**Comment by zenangst** [comment]
Hey @Din0Git, glad you like the app.
I'm unsure of the inner-workings of Parallels. Right now, you can only interact with things that have a place on the file system. I won't rule anything but it warrants some additional research to give a proper answer. Does Parallels produce any shortcuts in macOS file system?

**Comment by Din0Git** [comment]
Hi @zenangst, 
I would think it is possible, other programs like Karabiner Elements and Alfred hotkeys only work when coherence mode is active (that makes a windows-app work just like a Macos-app on screen). Karabiner Elements and Alfred both use the bundle identifier to see if the application is the front most window but could also use the file path i think. 

As an example with the help of Karabiner Viewer i looked up the windows explorer window (shortcut part that Parallels produce on the macOS file system)

Bundle identifier
com.parallels.winapp.f731d721a28bc78c6f67e277c8918c19.2ffcb03ebc324fac9173f307f318b183

User/Path
/Users/dino/Applications (Parallels)/{2ffcb03e-bc32-4fac-9173-f307f318b183} Applications.localized/Verkenner.app/Contents/MacOS/WinAppHelper

(Global) KeyboardCowboy hotkeys also work in the windows-apps so think the only part that is missing to making this work is the function to select a custom application with the help of the bundle identifier or the user path. Maybe by adding a browse to your folder/file window at the bottom of the application trigger?

**Comment by zenangst** [comment]
@Din0Git One thing that you could try is to add the application that you want to open using the `Open Command`.

I'm gonna look into adding support for custom application paths, it would mean a tiny bit mor work, but it can be worth it.

**Comment by zenangst** [comment]
@Din0Git I haven't forgotten about this issue, will see when life allows me to install Parallels and dig into some of the details. I think we should be able to do this. Even if I don't use Parallels, I think it could be a nice addition.

**Comment by Din0Git** [comment]
@zenangst no problem! That is how life works ;)
Global hotkey’s already work. The only thing is if you want to make a hotkey for a specific application. The parallels application are not found by the autodiscovery of KeyboardCowboy. I don’t no if it is possible to select a custom path to an application? I think that would fix the ‘issue’

**Comment by zenangst** [comment]
@Din0Git did you try adding an Open command and point that to the application?

**Comment by Din0Git** [comment]
@zenangst

Do you mean 
New workflow —> Application of keyboard —> add a command —> open or close app. —> open —> select application? 
If that is the case then the same applications are showing. 

Or do you mean something else?

**Comment by zenangst** [comment]
@Din0Git I was thinking this command: 
<img width="983" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/57446/da76ea33-f886-47c1-b59e-399072590d7b">

**Comment by Din0Git** [comment]
@zenangst

:) found it after I posted the message. 
I tried making a hotkey to open a parallels application and that works (if the application is already running it comes to the front). 
Only think now is to make it possible that if the custom path is front most window that hotkey do this

**Comment by zenangst** [comment]
Hey @Din0Git, just wanted to post a small update. I've been looking into adding support for additional search directories.

I've added a new preference pane that looks like this:
<img width="592" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/57446/015c3e21-6909-40cd-9886-5a3575145470">

I also went the extra mile and installed Parallels, so this is what it looks like in action:

https://github.com/zenangst/KeyboardCowboy/assets/57446/6caf0f45-a166-428a-b9a3-3b2a4ec7dc3b

Hope this is what you were looking for.

**Comment by Din0Git** [comment]
Hey @zenangst,Looks great and exactly what I was looking!!!Can I help testing 😉Verstuurd vanaf mijn iPhoneOp 30 sep 2023 om 17:21 heeft Christoffer Winterkvist ***@***.***> het volgende geschreven:﻿
Hey @Din0Git, just wanted to post a small update. I've been looking into adding support for additional search directories.
I've added a new preference pane that looks like this:

I also went the extra mile and installed Parallels, so this is what it looks like in action:
https://github.com/zenangst/KeyboardCowboy/assets/57446/6caf0f45-a166-428a-b9a3-3b2a4ec7dc3b
Hope this is what you were looking for.

**Comment by zenangst** [comment]
@Din0Git oh, fantastic. Then we are on the right track.
Shouldn't be took long until I can wrap it up and make a new release.
I do have some extra tidbits that I want to figure out with general caching of KC before I do a release (as some extra sugar on top 😊).

We also need to splash a bit of design on this to make sure that it looks up to par with the rest of the app.

Thanks for sparing on this, I think that this can be super useful for a lot of people that rely on Parallels in there day to day workflows.

**Comment by Din0Git** [comment]
@zenangst,Glad I could help and i think it’s a nice feature to have! Verstuurd vanaf mijn iPhoneOp 30 sep 2023 om 17:30 heeft Christoffer Winterkvist ***@***.***> het volgende geschreven:﻿
@Din0Git oh, fantastic. Then we are on the right track.
Shouldn't be took long until I can wrap it up and make a new release.
I do have some extra tidbits that I want to figure out with general caching of KC before I do a release (as some extra sugar on top 😊).
We also need to splash a bit of design on this to make sure that it looks up to par with the rest of the app.
Thanks for sparing on this, I think that this can be super useful for a lot of people that rely on Parallels in there day to day workflows.

**Comment by zenangst** [comment]
Made a PR here - https://github.com/zenangst/KeyboardCowboy/pull/401
So we are almost ready to ship and update 🚢

**Comment by zenangst** [comment]
@Din0Git the new version is out now 😁 
https://github.com/zenangst/KeyboardCowboy/releases/tag/3.15.0

**Comment by Din0Git** [comment]
@zenangst,Nice! Installed it but I’m a bit confused. How do I use it? Forgive me I’m new to KC, for example: keybinding Shift D when windows notepad is open the send Shift S. There are no parallels apps showing under application (don’t know if that is still the way it should be). Verstuurd vanaf mijn iPhoneOp 1 okt 2023 om 16:55 heeft Christoffer Winterkvist ***@***.***> het volgende geschreven:﻿
@Din0Git the new version is out now 😁
https://github.com/zenangst/KeyboardCowboy/releases/tag/3.15.0

**Comment by zenangst** [comment]
You'll have to open the applications settings and add the directory.

<img width="1056" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/57446/32762e18-051e-40db-8091-6c94ea266e98">

When you've done that, your Parallels apps should show up.

**Comment by Din0Git** [comment]
@zenangst looks easy when you know what you are doing ;) thanks for the quick reply and the awesome work! Verstuurd vanaf mijn iPhoneOp 1 okt 2023 om 17:46 heeft Christoffer Winterkvist ***@***.***> het volgende geschreven:﻿
You'll have to open the applications settings and add the directory.

When you've done that, your Parallels apps should show up.

**Comment by zenangst** [comment]
No worries mate, I'm looking into adding more "in-app" descriptions and "what's new", in addition to updating the wiki with more information about how to use the app :)
