### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by panckreous** [zenangst/KeyboardCowboy#383]
This looks really promising so far. Are there any plans for documentation and examples? And/or a way to get notified when they are available?

**Comment by zenangst** [comment]
Hey @panckreous, yeah that is definitely on my list.
Right now I've been hammering away on the website, which you can view here - https://zenangst.github.io/app/keyboardcowboy/

Keep in mind that this is a work in progress but I intend to document and share some inspiration both here on GitHub and on the website itself.

If you have any questions, don't be afraid to ask ❤️

**Comment by zenangst** [comment]
Hey @panckreous

I've started building the wiki here on GitHub.
You can find it here - https://github.com/zenangst/KeyboardCowboy/wiki
