### ISSUE TITLE
Add minimum system requirements to readme

### ISSUE THREAD

**Issue by splorp** [zenangst/KeyboardCowboy#420]
There is no mention of what the minimum macOS system requirements are for this utility.

Could you please add something to the readme regarding this?

Thanks.

**Comment by zenangst** [comment]
@splorp good idea, I'll update the README with that info.
We currently target macOS Ventura.

**Comment by zenangst** [comment]
Added it to the README now, thanks for pointing this out ❤️

**Comment by splorp** [comment]
Thanks so much!

**Comment by gingerbeardman** [comment]
Was there ever a version to support macOS 12?

**Comment by zenangst** [comment]
@gingerbeardman yeah that was a previous pre-release version which is WAAAAAY behind the current version:

```[1086 commits ](https://github.com/zenangst/KeyboardCowboy/compare/0.16.1...main)to main since this release```

Can't really speak for the quality of that version.

**Comment by gingerbeardman** [comment]
Sadly I'm on Monterey so I'll take what I can. 

I mention the app in this blog post: https://blog.gingerbeardman.com/2023/12/23/using-game-controllers-and-keyboards-for-custom-shortcuts/
