### ISSUE TITLE
In “open app” list, not all apps are shown

### ISSUE THREAD

**Issue by Cykelero** [zenangst/KeyboardCowboy#465]
When creating a new “Open app” action, many of my apps are absent from the list, so I can't select them as a target for the action.

It seems that Keyboard Cowboys populates its list based on known locations (like `/Applications`), but maybe non-recursively?
Most of my apps are filed in subfolders of the Applications folder:
![2023-12-07 16 41 58 Finder app (Applications)](https://github.com/zenangst/KeyboardCowboy/assets/2979318/f47bfa3b-2d93-4baa-84c6-2f540f19e96b)

**Comment by zenangst** [comment]
Hey @Cykelero, if it doesn't show up in the list, you can add additional search directories inside of Settings.

<img width="592" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/57446/ce21ff52-c689-450c-aca0-bb39a6c6981c">

**Comment by zenangst** [comment]
Just to clarify, we do search further than one level, but we opt out to avoid going to deep.

**Comment by Cykelero** [comment]
That worked, thanks!

Of note:
- After adding the folder to the list, I had to restart Keyboard Cowboy for the list to be updated with the added apps
- When adding a folder, it doesn't seem like you can select more than one at once

**Comment by zenangst** [comment]
@Cykelero thanks, I’m gonna get that sorted 😎
