### ISSUE TITLE
KC is automatically turned off on my mac. 

### ISSUE THREAD

**Issue by gn121259** [zenangst/KeyboardCowboy#469]
When I execute KC, It works appropriately.
However, KC turned off automatically after a few minutes.

**Comment by gn121259** [comment]
Here is my crash reports for KC. 

I hope that this is helpful for you. 


Best,

Inhyuk 


￼

**Comment by zenangst** [comment]
@gn121259 Doesn't look like the attachment worked when replying via email. Would you mind trying to attach it again?

**Comment by gn121259** [comment]
![Keyboard Cowboy-2023-12-11-183114](https://github.com/zenangst/KeyboardCowboy/assets/97204403/3d05eca5-bfdc-4d7b-9da4-e2f10fa92db3)

I changed .jps -> .png because git doesn't support .jps.

**Comment by zenangst** [comment]
Hmm, still can't see the attachment. Just a broken reference.

**Comment by gn121259** [comment]
[crash_report.txt](https://github.com/zenangst/KeyboardCowboy/files/13634968/crash_report.txt)

This is my last try.... 
I copy the report to txt file.
I don't mean to bother you.

**Comment by zenangst** [comment]
Thanks a lot @gn121259, I'll get cranking on figure out what is going wrong here and push an update, when life allows ❤️

**Comment by zenangst** [comment]
@gn121259 I made an attempt to fix the crash in the latest version, you can grab it here: https://github.com/zenangst/KeyboardCowboy/releases/tag/3.20.0

**Comment by gn121259** [comment]
I tried new version of KC and finally error didn’t happen. 

Thanks you for your quick response to my issue. 

Have a good day.

**Comment by zenangst** [comment]
@gn121259 You are welcome, and thank you for bringing this to my attention and following up ❤️
