### ISSUE TITLE
Text Command in Typing mode omits the @, $ and ^

### ISSUE THREAD

**Issue by brfransen** [zenangst/KeyboardCowboy#470]
Some characters are not printed by the Text Command in typing mode.

**Comment by zenangst** [comment]
@brfransen  Oh, interesting. I've found some bugs related to typed input in the past, but those were suppose to be fixed by now.

Can you provide which keyboard layout you are using so I can try and replicate the issue locally.

**Comment by zenangst** [comment]
@brfransen was able to reproduce it, working on a fix now.

**Comment by brfransen** [comment]
> @brfransen was able to reproduce it, working on a fix now.

U.S.
