### ISSUE TITLE
Can't seem to open the app

### ISSUE THREAD

**Issue by asgeirtj** [zenangst/KeyboardCowboy#477]
Nothing happens

**Comment by zenangst** [comment]
@asgeirtj it doesn't appear in the menubar?

**Comment by zenangst** [comment]
If the app is crashing at startup, are there any crashlogs that you can share?

**Comment by zenangst** [comment]
@asgeirtj any updates on this issue?

**Comment by asgeirtj** [comment]
seems to have resolved itself, im on 14.3 developer beta so might be
releated, in any keys before and after the only way for me to open the app
is to search it using bartender finder
