### ISSUE TITLE
Problem changing system permissions during install

### ISSUE THREAD

**Issue by jromero2k** [zenangst/KeyboardCowboy#478]
Installed the app using `brew`, but something is failing during install after I click the "Request permission" button... when it tries to set up the Accessibility permissions, a spinning wheel shows for a while and then it's replaced with "Unknown"

**Comment by zenangst** [comment]
He @jromero2k, wow... I wasn't aware that someone added this to Homebrew, that is nice. I'll have to investigate this further, does the same thing happens if you install it via GitHub download?
