### ISSUE TITLE
Nested Binding

### ISSUE THREAD

**Issue by AjayShanker-geek** [zenangst/KeyboardCowboy#481]
Possible configuration:

Binding `hyper + c` then `w`: Whatsapp (c for communication )
Binding `hyper + c` then `s`: Slack

**Comment by zenangst** [comment]
Hey @AjayShanker-geek,
That is absolutely possible, Keyboard Cowboy supports keyboard sequences and you can even go as far as to scope them to an individual application.

Here an example where I tap `fn-A` followed by `fn-K` to open or switch to Kaleidoscope:

<img width="1068" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/57446/5952ece7-1821-45ef-ba44-89f07a4c3b67">

**Comment by AjayShanker-geek** [comment]
My mistake, I retried with sequentially and it WORKS. Loving ur project

**Comment by zenangst** [comment]
@AjayShanker-geek thanks mate, that means the world to me, if you have any run into an issue or have ideas for the future, be sure to let me know ❤️
