### ISSUE TITLE
Difficulties in customization. Shortcuts do not work in all keyboard layout, I must it set En

### ISSUE THREAD

**Issue by EntonyHop** [zenangst/KeyboardCowboy#483]
Hi, Chris. Thank you sooo much for a really cool multi-functional app, it has become like a second swiss knife for me, after the ReyCast. But this I've only mastered the shortcuts for apps and links so far.

1.Accidentally deleted all presets (examples) from some tabs, and now I can't figure out how to customize. The wiki has too general information, no examples. And there is no function to return default settings in the program. I'm interested in these are the kind of settings you mentioned on reddit: 
a." also utilize shell scripts to alter the screen resolution, adjusting it according to my need for more or less screen space." 
b."A Hotkey for toggling low power mode on or off"

2. And one more, a very big problem shortcuts work only on the English layout, please add ability to work on any layout 

P.S.: It's like you read my mind, I use low power mode a lot and wanted to set up a quick resolution switch to work in the Final Cut, and then I saw your one-of-a-kind post.

**Comment by zenangst** [comment]
Hey @EntonyHop 

No need to thank me, I just made this app to scratch my own itch... and boy have I been scratching itches for a long while now 😆 (The app turns 12 years this year).

Yeah, I've been meaning to update the Wiki with a lot more examples, tips and tricks. Just haven't gotten around to doing that. Poor excuse, but it its the only one I got.

### Switching Resolutions

To switch resolution on my laptop, I wrote a small Swift script called Retina (https://github.com/zenangst/Retina).

With that binary installed, I can then invoke it from Keyboard Cowboy.
This is what my setup looks like:

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/214b4cad-e294-45f6-9ae5-5abe4c3ac595)

Note that I haven't test Retina on anything other than the built-in display (I almost never used an external monitor).

### Low Power Mode

Low power mode needs some extra permissions, so here I simply piggy-back on Shortcuts.

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/c6b119dc-3d28-4273-bf5a-6ab63e8da34f)

This is what the command looks like for me in Keyboard Cowboy

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/846a3772-c25d-418f-b646-9d19cd6758bf)

### Layouts

Could you provide a bit more information about which layouts that aren't working?
I use Keyboard Cowboy with a Swedish layout (and the occupational Norwegian layout, as I'm a Swed living in Oslo).

Shortcuts are bound to key codes, so if the layout changes, the same keys won't produce the same key codes. So, if you switch the layout, the key codes that you send to the system changes. I'm curious if this is the case that you are seeing.

Even if I said that you didn't have to thank me, it doesn't mean that it doesn't warm my heart that you find this useful. ❤️

Hope you find the information useful.
If you want to spare or share ideas then you could just start a discussion here - https://github.com/zenangst/KeyboardCowboy/discussions

**Comment by EntonyHop** [comment]
THX a lot!
>Could you provide a bit more information about which layouts that aren't working? 
I use Russian (both PC and Mac), Ukrainian (both PC and Mac) 
>Shortcuts are bound to key codes, so if the layout changes, the same keys won't produce the same key codes
Roger that, now I've duplicated the command and added the same Russian layout. 
PS: In the new version 3.21.2 the green "add command" button is broken and does not respond to pressing it

**Comment by zenangst** [comment]
@EntonyHop which button are you referring to? The one in an empty list or the one to add to existing workflows?

A screenshot would be helpful ❤️

**Comment by zenangst** [comment]
Are you one Ventura or Sonoma?

**Comment by EntonyHop** [comment]
>which button are you referring to? The one in an empty list or the one to add to existing workflows?
this one 
<img width="178" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/99942084/9d458851-4672-4017-ab6e-ab5ea1e8647c">
I was trying to record a video of the screen, but the button is already working, all is well
>Are you one Ventura or Sonoma?
yes

**Comment by zenangst** [comment]
@EntonyHop so now everything is fine? ¯\_(ツ)_/¯ 
Okay, I'll just go ahead and close the issue 😁
