### ISSUE TITLE
App wont launch at all

### ISSUE THREAD

**Issue by yonahf** [zenangst/KeyboardCowboy#490]
Macbook Air M2
Sonoma 14.2.1
Doanloaded the app, tried to launch, asks if it can update, then......nothing. No app window, no taskbar....nothing

**Comment by zenangst** [comment]
Hey @yonahf, Interesting, that's a new one.
Do you have any logs that you can share?

**Comment by yonahf** [comment]
Where would I find those?

**Comment by zenangst** [comment]
@yonahf check Console.app (/Applications/Utilities/Console.app).

Check if you can find anything under either Crashes, or by checking the system logs while opening Keyboard Cowboy. Maybe that could give use some hints to what might be going wrong here.

**Comment by yonahf** [comment]
I checked and even searched all avenues for “keyboard” but nothing came up

**Comment by yonahf** [comment]
I have a small suspicion that my work laptop has something blocking it, but
my manager says that because I’m IT the only thing that’s special on mine
is that I have to use chrome browser

**Comment by zenangst** [comment]
@yonahf did you manage to figure this out?
Seems odd that there is zero trace of the app in the logs if Keyboard Cowboy is not allowed to run (based on the security settings).

Hope you figure it out.

**Comment by yonahf** [comment]
I think so, let me hit you back tomorrow

**Comment by edsonbittencourt** [comment]
The same here. I noticed that if I reinstall and before opening it for the first time, run `codesign --force --deep -s - /Applications/Keyboard\ Cowboy.app`, it opens. But after I close it and try to open it again, it doesn't work anymore.

**Comment by yonahf** [comment]
I suspect I may have some sort of blocker with my corporate MDM.  Even though I senior IT, and should have limited profile control, I noticed that while I was able to export the shortcuts from my keyboard text replacement tool, I was not able to Import. I wonder if the same keyboard/input/system mod block is affecting keyboard cowboy.

**Comment by zenangst** [comment]
@edsonbittencourt did you install it via GitHub or Homebrew?
Never encountered this myself 🤔

**Comment by yonahf** [comment]
Via the dmg

**Comment by edsonbittencourt** [comment]
Using .dmg. It's been a while since I've been able to use the app.

**Comment by zenangst** [comment]
@edsonbittencourt Very odd, I haven't made any changes to the code signing. And when I inspect the app, everything seems correct with it being notarized 🤔

**Comment by yonahf** [comment]
Im not sure what y’all fixed but the new version works on my computer….so far

**Comment by zenangst** [comment]
@yonahf good to hear, we haven't changed anything when it comes to the build pipeline 🤷

**Comment by zenangst** [comment]
@edsonbittencourt any updates on your end?

**Comment by edsonbittencourt** [comment]
@zenangst sorry for the delay in responding. unfortunately, I still haven't been able to get the app working here... but I also won't be able to stop to analyze and focus on this right now, feel free to close the issue. when I get a moment, I'll come back with news and update you. thanks so much, and congrats on the project, it's amazing!
