### ISSUE TITLE
open always a new window (iterm2) with hotkey not working

### ISSUE THREAD

**Issue by bforpc** [zenangst/KeyboardCowboy#491]
Hi,

i love this app. 
But i need to open iterm2  always a new window and not focus the already opened one.
I had try all options ... Using MacOS Sonoma 14.2.1

Bfo

**Comment by zenangst** [comment]
Hey @bforpc,

Did some digging, how about this:

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/b09b22ff-6186-4e89-b446-3ab4d5844e5f)

This will open a new window for iTerm when ever I run that shortcut.

**Comment by bforpc** [comment]
Hi,

sorry for that bad question: How do I put it into that field?
If i wrote "New Window with Current Profile" there, then nothing happen.

![2024-02-12_08-19](https://github.com/zenangst/KeyboardCowboy/assets/5180591/632d6932-d2b7-4631-818f-2e92ee5f2839)

My Shortcat always focus the already opened Window.

Bfo

**Comment by zenangst** [comment]
For it to find the actual UI element "New Window with Current Profile". I'll need to add an invocation for the root element, in this case `Shell`.


It should look something like this:

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/b710b514-8959-4426-bf4c-40c9366375e2)

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/8ef5d9ff-32c3-44bf-af21-cccf47f2345c)

**Comment by bforpc** [comment]
Hi... thank you very much.
After pressing the hotkey, then the already opened window will be focused and after that a new window will be open.
This works... it is a little bit tricky to configure (for the first time), but it works!!!

Again, thanks. I will donate right now  a little to your project (and your help)


Bfo

**Comment by zenangst** [comment]
@bforpc yeah it will have to focus the application (which will focus the current window) in order to be able to use the applications menu bar. This is just what the system does by design.

Glad you got it working ❤️

**Comment by zenangst** [comment]
Hey @bforpc, I have an update that I think you'll really enjoy.

Basically, I improved the menubar commands by adding an optional target application.
In your case, you would target iTerm.. then it would activate and run the menu bar command on that specific app. This eliminates the need to use a sequence of commands and it won't focus in the currently open window, just open a new one for you.

I hope this is what you where after.

This is the pull request (has some screenshots attached to it) https://github.com/zenangst/KeyboardCowboy/pull/498

**Comment by zenangst** [comment]
It will make its way into the next release.

**Comment by zenangst** [comment]
Hey @bforpc, `3.22.1` is out with the latest change to `Menu Bar Commands`. Enjoy 😎

**Comment by bforpc** [comment]
thanks al lot. I try iot out later today / tomorrow.

THX
