### ISSUE TITLE
Key shadows stills on screen

### ISSUE THREAD

**Issue by alegreiff** [zenangst/KeyboardCowboy#496]
When I execute a shortcut the key combinations remains visibles on screen

**Comment by zenangst** [comment]
@alegreiff just to clarify, is it from the notification?
Mind sharing a screenshot?

**Comment by zenangst** [comment]
The UI has gotten a redesign in the upcoming version, so I think this will resolve itself. Stay tuned.

**Comment by zenangst** [comment]
@alegreiff still an issue with the latest version and redesign?
