### ISSUE TITLE
mouse doesn't work in workflow

### ISSUE THREAD

**Issue by bassamsdata** [zenangst/KeyboardCowboy#500]
Firstly, I want to express my gratitude for this amazing app. It's been incredibly helpful so far.

I've encountered a couple of issues that I wanted to bring to your attention:

I'm unable to click in the workflow area and choose other workflows. Although I was able to create a new one, I can't switch to a different workflow at all (mouse seem don't work in the workflows)

https://github.com/zenangst/KeyboardCowboy/assets/105807570/3a2fb725-e8a2-4592-b3dd-90f4ab5b3131

Additionally, the updater doesn't seem to be working properly. It immediately shows an error whenever I try to update. I've attempted to update to the current version by downloading and replacing the files, but the issue persists.

<img width="253" alt="Screenshot 2024-02-16 at 9 57 48 AM" src="https://github.com/zenangst/KeyboardCowboy/assets/105807570/67f050f5-5b02-447a-a25b-65c32e447f87">

Macos: 13.6.3
Version 3.22.0 (513)

Thank you for your attention to these matters.

**Comment by zenangst** [comment]
Hey @bassamsdata I just tried checking for updates on my machine. It works as intended 🤔

I'll have to test the selections on macOS Ventura (I'm on Sonoma myself). I'll get back to you on that.

**Comment by zenangst** [comment]
Hey @bassamsdata, we just released 3.22.1 which should fix the issue with workflows not being selectable.

**Comment by bassamsdata** [comment]
thank you for the prompt fix. it works fine now
