### ISSUE TITLE
Language agnostic keyboard shortcuts

### ISSUE THREAD

**Issue by amatoenot** [zenangst/KeyboardCowboy#504]
It would be nice to have language-agnostic keyboard shortcuts. It seems all other system shortcuts work with key codes instead of actual symbols, so the input source doesn't matter, which is not the case with the Keyboard Cowboy. Currently, as a workaround, I have to duplicate actions to have shortcuts working in both languages.
<img width="176" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/17862456/5e2510c1-f0dc-451b-824d-6f4586eeadc2">

**Comment by zenangst** [comment]
Hey @amatoenot, unsure how you would make this agnostic as the underlying key codes sent by the keys varies depending on which layout you are using.

Could you elaborate how this would work in practice?

**Comment by amatoenot** [comment]
Hi @zenangst,
Not sure exactly. Afaik keyboard key HID is the same for any language. So maybe it's possible to create shortcuts mapped to the key HID somehow. Most of the default mac os shortcuts work this way (e.g. 'CMD + C key' copies in any language)

**Comment by zenangst** [comment]
I haven't found any information about HID related information on `CGEvent`'s (which we are using to identify events).

https://developer.apple.com/documentation/coregraphics/cgeventfield

**Comment by zenangst** [comment]
That is what is used to identify it today, but the current input source send different key codes for different keys depending on the layout.

**Comment by ww7** [comment]
For users with multiple language keyboard layout it's a pain to manage.
I'm using 3 languages and it will be mess.
All keyboard shortcuts managers that I used over decades is language-agnostic.
Maybe [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements) source code will be helpful?

**Comment by zenangst** [comment]
I looked into the source code of [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements) and they use a kernel extension which is a completely different integration level than Keyboard Cowboy.

But I'll continue to investigate to see if this can be done with the current mach port implementation.

**Comment by ww7** [comment]
Maybe such old project can help? (sorry, I'm don't have any experience on macOS programming)
https://github.com/shortcutrecorder/shortcutrecorder

**Comment by zenangst** [comment]
Took a quick glance at `[shortcutrecorder](https://github.com/shortcutrecorder/shortcutrecorder)`. Seems like that also is dependent on the current layout of the keyboard when mapping.

Note that I didn't do a deep-dive.

**Comment by ww7** [comment]
Found some links related
https://stackoverflow.com/questions/3202629/where-can-i-find-a-list-of-mac-virtual-key-codes/16125341#16125341
https://stackoverflow.com/questions/1918841/how-to-convert-ascii-character-to-cgkeycode

**Comment by ww7** [comment]
Wow, the new version seems keyboard language agnostic! Thanks!!
