### ISSUE TITLE
When launching a second time make it open the Configuration window

### ISSUE THREAD

**Issue by bjrmatos** [zenangst/KeyboardCowboy#511]
right now to open the configuration window, you have to launch Keyboard Cowboy, go to the menu bar, click and select "Open Keyboard Cowboy", this is a bit of a problem when you use Bartender (which let you hide some icons in the menu to avoid getting cluttered), when using it you have to do even more steps.

what i think it will be a good idea is that if you launch Keyboard Cowboy when it is already launched, then the configuration window should be opened, just like it will happen when you click "Open Keyboard Cowboy" from menu bar. 

i have saw other applications doing this, the one i can remember is CleanShoot X, first time it just launchs the app you get it running and get the menu bar icon, the second time you launch it knows you want to configure it and open its editor directly. it is likely a common pattern for apps that live in the menu.

**Comment by zenangst** [comment]
@bjrmatos Never thought about this because I've added a global keyboard shortcut in Keyboard Cowboy to open Keyboard Cowboy (talk about inception 🤣).

I'll do some digging, supporting this should be pretty straight forward.

**Comment by zenangst** [comment]
@bjrmatos This was easy enough to implement, 4 lines of code.
It will make its way into the next release 😎

**Comment by bjrmatos** [comment]
awesome, glad to hear that, thank you!! 🚀

**Comment by zenangst** [comment]
@bjrmatos would you mind taking 3.23.1 for a spin to verify if this is fixed now?
https://github.com/zenangst/KeyboardCowboy/releases/tag/3.23.1

**Comment by bjrmatos** [comment]
looks great now, thanks for the improvement
