### ISSUE TITLE
Using same key in combinations as sequence does not always work

### ISSUE THREAD

**Issue by bjrmatos** [zenangst/KeyboardCowboy#512]
example case:

i create an alias for ⇧⌘A (this keyboard shortcut trigger a Search Tabs window) in Chrome for it to be a sequence "⌥F ⌥F"

![Screenshot 2024-03-13 at 2  14 06@2x](https://github.com/zenangst/KeyboardCowboy/assets/4262050/6ffa5270-34ac-447b-806d-7014ca4581b0)

however i've noticed that it does not work in specific cases: 

- if you hold "⌥F", keep pressing ⌥ but release F, and hold F again, it does not make it trigger. this seems to be an issue when using the same key F in the sequence, because for other combinations that don't use same key it works, like "⌥D ⌥F" (holding "⌥D", keep pressing ⌥ but releasing D, then pressing F). what only makes it trigger in this case is hold "⌥F", release both "⌥" and "F" then hold "⌥F", basically if you want to keep you finger in the "⌥" then it won't work when using the same key "F" in the sequence

- if i change the keyboard shortcut to be now "⌥F F", this makes it even worse, now it does not trigger most of the time, and it is a matter of some luck to get it activated, again if i use a sequence with different key like "⌥D F", it is not an issue.

a general video showing the case: https://share.cleanshot.com/9rfXyZ8H

**Comment by zenangst** [comment]
Interesting observation, I'll take a deep-dive into how we resolve sequences with duplicate keys. Might be a small 🐛 in there somewhere.

I'll do some digging and get back to you.

**Comment by zenangst** [comment]
@bjrmatos I recreated your setup and can reproduce the issue.
I'll keep you posted on the progress.

**Comment by zenangst** [comment]
@bjrmatos Good news, I think I figure out what is going on and have a fix for the upcoming version.

**Comment by bjrmatos** [comment]
it is working now, thanks, this is a great improvement for me, I've tried everything to have keyboard chords (like the ones in vscode) working on macOS level, Keyboard Cowboy is the one that does it the best.

**Comment by bjrmatos** [comment]
i have a question, if i have "⌥F ⌥F" sequence setup, but only press the first "⌥F", if i don't press any other key, is there a timeout in which i can press the second "⌥F"? during my test i think i get like 7-8s but wanted to confirm. related to this, do you think it is a good idea to show some kind of indicator (as an option) that the sequence has started?

i mean, for example in vscode if you press the first part of a chord/sequence you get this in status bar:

![Screenshot 2024-03-15 at 12  03 04@2x](https://github.com/zenangst/KeyboardCowboy/assets/4262050/d0f475c0-bc2c-485e-b57c-23f323259c03)

in Cowboy case maybe what works best is some kind of little float message with just the keys pressed, but just wanted to share the idea, just in case you find it useful.

**Comment by zenangst** [comment]
@bjrmatos Right now we don't have a timeout, but if you activate a bundle/sequence, you can always tap on the Escape keep to get out of it.

You can enable bundle notifications in the application settings.

![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/287b8182-6944-4ecb-b766-67faa0ed5d22)

**Comment by bjrmatos** [comment]
> Right now we don't have a timeout, but if you activate a bundle/sequence, you can always tap on the Escape keep to get out of it.

great, thanks, that should be enough for me.



> You can enable bundle notifications in the application settings.

interesting, i will give it a try, though not a big fan of seeing an empty circle when not having something to show, but let's see i will experiment with it

![Screenshot 2024-03-15 at 1  44 42@2x](https://github.com/zenangst/KeyboardCowboy/assets/4262050/3e0cb8d8-104c-4541-a164-8e92b466adc6)

**Comment by zenangst** [comment]
We can add a feature to hide it entirely when it is empty.
I'll add it to the backlog 😎

**Comment by bjrmatos** [comment]
> We can add a feature to hide it entirely when it is empty.
> I'll add it to the backlog 😎

sounds great!!


sorry to spam the github issue, but since we are already talking about the notification, something i want to mention:

https://share.cleanshot.com/ryPGwcnd

in the video i am activating the "testing" user mode with "⌥K ⌥U", however since i have other keyboard sequences with the "Show bundles" notification enabled, the "testing" user mode notification gets hidden, likely just need a bit of reorder so the notifications get stacked or something like that

**Comment by zenangst** [comment]
No worries @bjrmatos, I’ll look into it. Don’t be shy to bring this to my attention, the outcome is that we get a better product ❤️

**Comment by zenangst** [comment]
@bjrmatos did a bit of work on this issue now, the tiny dot won't show up in the upcoming version 😎

**Comment by bjrmatos** [comment]
awesome, thanks for the quick fixes
