### ISSUE TITLE
Make the configuration window remember its last position and size

### ISSUE THREAD

**Issue by bjrmatos** [zenangst/KeyboardCowboy#517]
it will be nice if the configuration editor window remembers its last size and position, right now if you open the editor, make it bigger, move it t, close it, and open it again it just goes back to the default/initial size and position which is a bit annoying when you are used other macos apps remember your changes

**Comment by zenangst** [comment]
@bjrmatos going on holiday tomorrow but I'll add it to the todo list. Been working on getting Light Mode working this evening :)

I might look into this on the plane tomorrow, thanks for reporting ❤️

**Comment by zenangst** [comment]
Hey @bjrmatos, just wanted to post a minor update here.
I've managed to implement proper window frame restoration between launches and re-opening of the main window, it will make its way into the next version of Keyboard Cowboy 😎

**Comment by zenangst** [comment]
Spoke too soon, needs a little more work and some more testing for it to be just right.

**Comment by zenangst** [comment]
Hey @bjrmatos, 3.24.0 is out. Now Keyboard Cowboy should be a good buddy and remember both window size and position.

https://github.com/zenangst/KeyboardCowboy/releases/tag/3.24.0
