### ISSUE TITLE
Can not run Keybord Shortcuts that send F[1,2,3,4 ...] keys

### ISSUE THREAD

**Issue by bjrmatos** [zenangst/KeyboardCowboy#518]
i have ⌘F8 configured in iTerm to show/hide the iTerm, i want to alias that shortcut to ⌥K ⌥I in Cowboy, however when doing this the shortcut is not sent (nothing happens)

if i run the ⌘F8 from the configuration editor i get an error message

![Screenshot 2024-03-21 at 4  18 53@2x](https://github.com/zenangst/KeyboardCowboy/assets/4262050/f703338d-0668-42f3-97ec-9e6eb4c9950b)
![Screenshot 2024-03-21 at 4  18 29@2x](https://github.com/zenangst/KeyboardCowboy/assets/4262050/741490c7-c182-4b5e-8aa3-ac59fda334df)

when i try with other F[1,2,3..] keys behaves the same, also it seems it is not related to a keyboard sequence (⌥K ⌥I) because the same happens if i alias to ⌘+I for example.

video showcase: https://share.cleanshot.com/Q3GNTpNt

**Comment by zenangst** [comment]
Hey @bjrmatos, got back from vacation this week. I'm gonna take a look at this very soon and try to figure out what is going on here.

**Comment by zenangst** [comment]
Sorry for this taking so long @bjrmatos, I'm actively debugging this now :)

**Comment by zenangst** [comment]
Hey @bjrmatos, check this out!

https://github.com/zenangst/KeyboardCowboy/assets/57446/e12b1322-eaad-4d56-b896-6b6d6ea438d3

**Comment by bjrmatos** [comment]
awesome, thanks for fixing this!! seems to be working great

**Comment by zenangst** [comment]
@bjrmatos the new version is available for download now.
https://github.com/zenangst/KeyboardCowboy/releases/tag/3.24.2
Let me know how it goes :)

**Comment by bjrmatos** [comment]
works like a champ!
