### ISSUE TITLE
Support for conditional Rebinding

### ISSUE THREAD

**Issue by jiengup** [zenangst/KeyboardCowboy#519]
Love this application.

Is there any way to config conditional Rebinding?

e.g., set ctrl+t to rebind cmd+shift+l(toggle sidebar) just for Safari.app?

**Comment by zenangst** [comment]
Hey @jiengup thanks for the praise, it means the world to me ❤️ 

Absolutely, this is where groups really shine.
If you create a group called `Safari` and configure it with rule, than you can have the same shortcuts do different things depending on the front most application.

<img width="712" alt="image" src="https://github.com/zenangst/KeyboardCowboy/assets/57446/519ae453-5410-4b24-ba80-91c6f5c85619">

**Comment by jiengup** [comment]
> Hey @jiengup thanks for the praise, it means the world to me ❤️
> 
> Absolutely, this is where groups really shine. If you create a group called `Safari` and configure it with rule, than you can have the same shortcuts do different things depending on the front most application.
> 
> <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/57446/322200844-519ae453-5410-4b24-ba80-91c6f5c85619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTg3MjIsIm5iZiI6MTcxMzAxODQyMiwicGF0aCI6Ii81NzQ0Ni8zMjIyMDA4NDQtNTE5YWU0NTMtNTQxMC00YjI0LWJhODAtOTFjNmY1Yzg1NjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE0MjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ODRhNmU2ODU0MWU0MTkyNDk3NmZmMmQ0MjM5OTY0YWMzN2EyZTU0YzJhMzYwZTgwNWU3NWViZmNjZjMxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._JZKhkwK-fuax6NUyZgyqZ7MrWdIAnYHaLNF8AV-xP8">

OK! It absolutely works. That's amazing!
Thanks for your reply and I'll close this issue.

**Comment by ctf0** [comment]
@zenangst is there away to have it the other way around (black list), ex, make the group global but **dont** activate when any of the apps in the list is the frontmost app.
