### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by dokkaebi** [zenangst/KeyboardCowboy#523]
I'm not sure how else to describe this. I just installed KeyboardCowboy to try it out, and I'm just seeing a blank window. I'm able to create a group / workflow / command through the File menu, but they don't show in the main window. I'll attach a series of screenshots.

I'm on an M1 max macbook running Sonoma 14.4.1 (23E224), and I also tried it on an M1 mac mini. Are those supported? My KeyboardCowboy version is 3.24.0 (894).

<img width="1728" alt="Screenshot 2024-05-20 at 10 04 40 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/b0303671-3d9f-48d5-9869-4799a0ff451e">
<img width="1728" alt="Screenshot 2024-05-20 at 10 04 43 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/ee58cf78-c8fb-4af4-a8e9-bb1ebfb9e8be">
<img width="1728" alt="Screenshot 2024-05-20 at 10 04 53 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/2d5f9e2c-0803-412c-aaa7-1a7f683ca040">
<img width="1728" alt="Screenshot 2024-05-20 at 10 04 58 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/7fd85ad4-439b-4daf-9fcb-add3c6369ea8">
<img width="1728" alt="Screenshot 2024-05-20 at 10 05 00 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/e5568a8b-4cd2-4fb3-912b-dccecf299c33">
<img width="1728" alt="Screenshot 2024-05-20 at 10 05 05 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/1d91222c-ecec-4e0c-bada-f9ece877dc9c">
<img width="1728" alt="Screenshot 2024-05-20 at 10 05 09 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/479dc2f3-c895-4b9b-9222-b43229b2dbb0">
<img width="1728" alt="Screenshot 2024-05-20 at 10 05 28 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/1f1731f7-9b78-49bb-a6cb-653b65df7834">
<img width="1728" alt="Screenshot 2024-05-20 at 10 05 32 PM" src="https://github.com/zenangst/KeyboardCowboy/assets/1037130/ac8d7d3e-31fd-43f9-8ba6-d7ef033892a8">

**Comment by zenangst** [comment]
Hey @dokkaebi, interesting.
I wonder what went wrong here, have you given the application permissions, or did you just get a blank screen to begin with?

**Comment by leodbrs** [comment]
I give the application permissions and I have the same problem.
![image](https://github.com/zenangst/KeyboardCowboy/assets/81977224/06d96d43-a573-4f75-bcfe-04d0364a7df8)

**Comment by zenangst** [comment]
@dokkaebi @leodbrs I'll take a look and get back to you. Thanks for reporting this ❤️

**Comment by zenangst** [comment]
Oh, seems like a did a real boo boo.
Working on a fix now, I'll ping you when a new version is available.

**Comment by zenangst** [comment]
Hey @dokkaebi & @leodbrs, we've pushed out a new update here - https://github.com/zenangst/KeyboardCowboy/releases/tag/3.24.1

Hope this fixes the issue that you are seeing.

**Comment by leodbrs** [comment]
Thank you @zenangst 🙂

**Comment by dokkaebi** [comment]
Wow! Awesome! Yes, this fixed it. Thank you for being so responsive.
