### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bforpc** [zenangst/KeyboardCowboy#526]
Hi zenangst,

your project has been grown and i love it. 
With interest I read all you posts and anouncments with every new version.
In this, I will ask if there is an overall documentation to read about and use all features of KC?
(sorry if there is already, but I havent found it)

Best regards from Hamburg, Germany

Bfo

**Comment by zenangst** [comment]
Hey @bforpc, this is still very much a work in progress but you can find some information in the Wiki here - https://github.com/zenangst/KeyboardCowboy/wiki
