### ISSUE TITLE
Notifications not showing when active secondary (external) display

### ISSUE THREAD

**Issue by ww7** [zenangst/KeyboardCowboy#549]
Notifications not showing when active secondary (external) display

**Comment by zenangst** [comment]
I'm looking into using https://github.com/MrKai77/DynamicNotchKit for some of the notifications. Which ones have issues with the secondary display? The output from a command or the ones being displayed when a command is done running?

**Comment by zenangst** [comment]
@ww7  I think this out and a fix is coming in the next version.

**Comment by zenangst** [comment]
@ww7 3.25.0 just dropped, can you take that for a spin to see if that doesn't fix the issue that you are experiencing?

https://github.com/zenangst/KeyboardCowboy/releases/tag/3.25.0

**Comment by ww7** [comment]
It works with secondary display, thanks!

**Comment by zenangst** [comment]
@ww7 thanks for reporting back and glad that it worked!
