### ISSUE TITLE
Request to add the function of manually selecting App

### ISSUE THREAD

**Issue by ssfun** [zenangst/KeyboardCowboy#557]
Currently, the app only allows selection from the list, and some special apps are not indexed. I hope to be able to add them manually.

**Comment by Anju023** [comment]
try this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by zenangst** [comment]
@Anju023 Don't even try to distribute that crap...

@ssfun You can add additional directories in the preference.
<img width="1012" alt="Screenshot 2024-09-19 at 12 24 29" src="https://github.com/user-attachments/assets/1b55bedb-04a3-434b-a799-fb986e47acac">
