### ISSUE TITLE
can not delete workflow since last version

### ISSUE THREAD

**Issue by bjrmatos** [zenangst/KeyboardCowboy#561]
since 3.25.0 i can not longer right click a workflow to delete it.

is this a bug? or is there a new way to delete workflows?

**Comment by zenangst** [comment]
Yeah, this is definitely a bug.
You should still be able to use backspace to delete a workflow.

**Comment by zenangst** [comment]
Interesting...

<img width="953" alt="image" src="https://github.com/user-attachments/assets/7df76851-c990-4b56-a8ba-b9a682cbea93">

This is what I get.
Which macOS version are you on @bjrmatos ?

**Comment by bjrmatos** [comment]
Sonoma 14.6.1

![Screenshot 2024-10-28 at 12  59 52@2x](https://github.com/user-attachments/assets/09904c4d-30bf-4352-a18d-894611930450)

tried different methods to launch the menu, but no luck.

**Comment by zenangst** [comment]
Thanks @bjrmatos 
I’ll install a virtual machine and to try and fix this issue.

**Comment by zenangst** [comment]
@bjrmatos I've managed to reproduce this, seems like the context menu when using a `List` is broken under Sonoma. I think I made this change after updating to Sequoia.

So, I have yet to solve it but I'm working on a fix, I'll keep you posted.

Again, thanks for letting me know!

**Comment by bjrmatos** [comment]
thanks!!

> You should still be able to use backspace to delete a workflow.

FWIW this does not worth either, maybe this is a related bug too

**Comment by zenangst** [comment]
@bjrmatos Yeah, I think it is related. Aiming to do a release tomorrow, just need to verify that the F-keys are working again before it is pushed out to production.

I don't have a keyboard at home that has F-keys above `F12` 🤣

**Comment by zenangst** [comment]
@bjrmatos 3.25.1 is out which should fix this issue.

https://github.com/zenangst/KeyboardCowboy/releases/tag/3.25.1

**Comment by bjrmatos** [comment]
yes, i can confirm that with 3.25.1 i can delete workspaces again and the right click menu is back. thanks!!!
