### ISSUE TITLE
when launching Cowboy the second time does not always open the Configuration window

### ISSUE THREAD

**Issue by bjrmatos** [zenangst/KeyboardCowboy#564]
i noticed that launching Cowboy a second time does not open the configuration window if you have not previously opened the window using the "Open Keyboard Cowboy" from the menubar

![Screenshot 2024-10-29 at 11  52 39@2x](https://github.com/user-attachments/assets/31d059c6-beaf-4d66-bc79-291c3f61effd)

I've noticed this for because when starting my MacBook in the morning sometimes what i do is to review my shortcuts, but it does not work until i open it at least one time from the menubar

context: #511

**Comment by zenangst** [comment]
@bjrmatos Yeah I've noticed some strange behavior there. I intend to rewrite the main window logic, it feels a bit wonky right now.

**Comment by zenangst** [comment]
Hey @bjrmatos, could you try this in version 3.25.2?

https://github.com/zenangst/KeyboardCowboy/releases/download/3.25.2/Keyboard.Cowboy.3.25.2.dmg

**Comment by bjrmatos** [comment]
hmm, it seems last version is still not working

> but it does not work until i open it at least one time from the menubar

actually it looks a bit worse because this does not work anymore

https://share.cleanshot.com/k7cVGfdy

**Comment by bjrmatos** [comment]
not sure why is not shown in the video but i was trying to shown the version printed from the menubar, anyway just as the proof that i am on latest

![Screenshot 2024-11-05 at 2  21 44@2x](https://github.com/user-attachments/assets/577ecee1-bbb6-4867-b34b-37145c8fccbe)

**Comment by zenangst** [comment]
@bjrmatos oh interesting, which version of macOS where you using again?

**Comment by bjrmatos** [comment]
![image](https://github.com/user-attachments/assets/77989492-ea7a-4382-a459-6e29ef2d040a)

sorry for the trouble, i usually wait a bit longer before upgrading major macOS versions :)

**Comment by zenangst** [comment]
Thanks a bunch for the extra info, @bjrmatos! I think I've come up with a better way to get the desired behavior.

I'm heading to bed now, but I can probably whip up a pre-release version for you tomorrow if you'd like to give it a try.

**Comment by bjrmatos** [comment]
@zenangst sure, i am happy to test!

**Comment by zenangst** [comment]
@bjrmatos mind trying this pre-release, not much has changed other than when to open the main window.

[Keyboard Cowboy 3.25.3.dmg.zip](https://github.com/user-attachments/files/17650517/Keyboard.Cowboy.3.25.3.dmg.zip)

**Comment by bjrmatos** [comment]
nice!! it is working with this pre-release 🎉🎉🎉🎉

**Comment by zenangst** [comment]
@bjrmatos thanks for verifying, I'll get a proper release out later this evening 😎

**Comment by zenangst** [comment]
Just released `3.25.3`, closing this now.
Thanks for the help verifying this 🤘
