### ISSUE TITLE
Сhanging open url command doesn't work

### ISSUE THREAD

**Issue by fushugaku** [zenangst/KeyboardCowboy#568]
When i have a command to open url and I change the url in it - url stays the same.
I have to first remove old command and add a new one, then it works

**Comment by zenangst** [comment]
@fushugaku oh, a bug. I'll add it to my list for the next version.
Thanks for reporting this!

**Comment by zenangst** [comment]
@fushugaku here is a freshly brewed version that should fix the issue you are seeing with open commands.

[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17652190/Keyboard.Cowboy.3.25.4.dmg.zip)

Let me know how it performs :)

**Comment by zenangst** [comment]
@fushugaku I just released 3.25.4, let me know how it goes.
