### ISSUE TITLE
Can't confirm configuration selection to get started

### ISSUE THREAD

**Issue by novascreen** [zenangst/KeyboardCowboy#572]
There is no button to confirm the selection and keyboard navigation is not supported.

![image](https://github.com/user-attachments/assets/f00ffa30-cc85-4bfe-8917-26c14adf4dac)

Version 3.25.4 (2171)
MacOS Sequoia 15.1 (24B2083)

**Comment by zenangst** [comment]
Hey there, @novascreen!

Guess what? I recently made a complete overhaul of the window handling system. I think you stumbled upon one of my "little" mistakes. I'll quickly fix it up and send you a fresh version tomorrow. Thanks a bunch for reporting this, and sorry that this was your first impression.

**Comment by zenangst** [comment]
@novascreen would you mind trying this version?

[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17773580/Keyboard.Cowboy.3.25.4.dmg.zip)

**Comment by zenangst** [comment]
@novascreen  I just released 3.25.4, let me know how it goes.
