### ISSUE TITLE
Incorrect Application Name Sorting in Application Trigger

### ISSUE THREAD

**Issue by FischLu** [zenangst/KeyboardCowboy#574]
When I add a workflow and set the application trigger to choose an application, I noticed that Visual Studio Code appears in the list of applications starting with "C" instead of under "V." Software version 3.25.5
<img width="159" alt="image" src="https://github.com/user-attachments/assets/8e29c5d5-f91b-4b77-ad43-5bc96f4e7f63" />

**Comment by zenangst** [comment]
It seems like the sorting doesn't work on display names, which is a bit confusing. Thanks for pointing that out! 😊

**Comment by zenangst** [comment]
@FischLu this will be fixed in the next version, made a fix for it here - https://github.com/zenangst/KeyboardCowboy/commit/57243f92b0b3603fa2dba50f8c88c39b683ab82d

**Comment by FischLu** [comment]
great, thanks! @zenangst

**Comment by zenangst** [comment]
@FischLu working on some other minor fixes, might release a new patch version later today.
I'll keep you posted :)

**Comment by zenangst** [comment]
@FischLu new version is out :)

**Comment by FischLu** [comment]
@zenangst awesome, thanks!
